package com.edu.educational_system.controller;

public enum CommandName {
	CREATE_COURSE, REGISTER_PERSON, START_LESSON, GET_PARTICIPANTS, GET_STAFF, GET_AVERAGE_GRADE, GET_ALL_COURSES, OBFUSCATE_DATA, WRONG_REQUEST, SHOW_SPECIAL_COURSE_INFO
	

}
